services:
  db:
    image: postgres:15-alpine
    container_name: somar-ia-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: somar123
      POSTGRES_DB: somar_ia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
